- name: Ansible Playbook
  hosts: all
  become: yes
  tasks:
    - name: Apply Kubernetes Reso
      ansible.builtin.command:
        cmd: kubectl apply -f /var/lib/jenkins/workspace/newproject/mypod.yml
      delegate_to: localhost

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/mynewproject/index.html
        dest: /usr/local/apache2/htdocs
        mode: '0644'

