- name:ansible
  host:all
  become:yes
  task:
     - name: Copy file with owner and permissions
       ansible.builtin.copy:
         src: /root/workspace/mynewproject/index.html
         dest:  /usr/local/apache2/htdocs
         mode: '0644'
