- name: Ansible Playbook
  hosts: all
  become: yes
  tasks:
    - name: copymodule
      copy:
        src: /var/lib/jenkins/workspace/mynewproject/mypod.yml
        dest: /home/ec2-user
    - name: Apply Kubernetes Reso
      ansible.builtin.command:
        cmd: kubectl apply -f mypod.yml
      

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/mynewproject/index.html
        dest: /usr/local/apache2/htdocs
        mode: '0644'

