- name: Ansible Playbook
  hosts: all
  become: yes
  tasks:
   - name: Create Kubernetes cluster with kops
     ansible.builtin.command:
       cmd: kops create cluster --zones=ap-south-1a --name=ranjith.k8s.local --state=s3://k8s29

 

   - name: copymodule
     copy:
       src: /var/lib/jenkins/workspace/vickyproject/mypod.yml
       dest: /home/ec2-user
   - name: Apply Kubernetes Reso
     ansible.builtin.command:
       cmd: kubectl apply -f mypod.yml
