- name: Ansible Playbook
  hosts: all
  become: yes
  tasks:
  
    - name: copymodule
      copy:
        src: /var/lib/jenkins/workspace/vickyproject/mypod.yml
        dest: /home/ec2-user
       
    - name: Apply Kubernetes Reso
      ansible.builtin.command:
        cmd: kubectl apply -f mypod.yml
